# If you change any of the values, make sure to run build task to reflect the changes in dart code
# otherwise tests will fail and the data in dart code might not be up to date with this file
name: alrayada
description: "Work in progress..."
version: 0.0.1+1
repository: https://github.com/freshKernel/alrayada
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Packages
  intl: ^0.19.0
  path: ^1.9.0
  go_router: ^13.2.4
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  hydrated_bloc: ^9.1.5
  meta: ^1.10.0
  linkify_plus: ^6.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  web_socket_channel: ^2.4.5
  cupertino_stepper: ^0.2.1
  flutter_platform_widgets: ^6.1.0
  dio: ^5.4.3
  http_parser: ^4.0.2
  mime: ^1.0.5
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  cross_file: ^0.3.4+1
  # async: any
  # result_dart: ^1.1.1

  equatable: ^2.0.5
  logger: ^2.2.0

  fresh_base_package:
    git:
        url: https://github.com/freshplatform/flutter-fresh-base-package.git
        ref: main

  # For code generator
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Plugins
  url_launcher: ^6.2.6
  path_provider: ^2.1.3
  sqflite: ^2.3.3 # TODO: Replace sqflite with drift or floor
  connectivity_plus: ^6.0.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^10.1.0
  firebase_core: ^2.29.0
  firebase_crashlytics: ^3.5.1
  firebase_analytics: ^10.10.1
  firebase_messaging: ^14.8.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  dynamic_color: ^1.7.0
  image_picker: ^1.1.0
  image_picker_platform_interface: ^2.10.0
  # For using Android 13 photo picker
  image_picker_android: ^0.8.10
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  # build_verify: ^3.1.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0
  icons_launcher: ^2.1.7
  flutter_native_splash: ^2.4.0
  bloc_test: ^9.1.7
  test: ^1.24.9
  yaml: ^3.1.2 # For scripts/tests
  pubspec_extract: ^2.0.5
  # pubspec_generator: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    # Svg folder
    - assets/svg/icons/
    - assets/svg/payment_methods/

    # Images folder
    - assets/images/
    - assets/images/payment_methods/

    # Lottie folder
    - assets/lottie/no_internet/
    - assets/lottie/page_not_found/
    - assets/lottie/onboarding/
    - assets/lottie/auth/
    - assets/lottie/errors/
    - assets/lottie/no_data_found/
    
    - .env


flutter_gen:
  output: lib/common/gen/

  integrations:
    flutter_svg: true
    lottie: true

icons_launcher:
  image_path: "dev_assets/icon_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: false
    web:
      enable: true

flutter_native_splash:
  # Light
  image: "dev_assets/splash_logo.png"
  color: "#DEE2E2"

  # Dark
  image_dark: "dev_assets/splash_logo.png"
  color_dark: "#272727"
  
  # android_12:
  #   image: "dev_assets/splash_logo.png"

pubspec_extract:
  class_name: Pubspec
  source: pubspec.yaml
  destination: lib/common/gen/pubspec.g.dart
  format: true
  map_list: false