name: alrayada
description: "Work in progress..."
version: 0.0.1+1
repository: https://github.com/freshplatform/alrayada
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Packages
  intl: ^0.18.1
  path: ^1.8.3
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  hydrated_bloc: ^9.1.4
  meta: ^1.10.0
  linkify_plus: ^6.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  web_socket_channel: ^2.4.0
  cupertino_stepper: ^0.2.1
  flutter_platform_widgets: ^6.1.0
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1

  equatable: ^2.0.5
  logger: ^2.1.0

  fresh_base_package:
    git:
        url: https://github.com/freshplatform/flutter-fresh-base-package.git
        ref: main

  # For code generator
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Plugins
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_analytics: ^10.8.10
  firebase_messaging: ^14.7.20
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0
  icons_launcher: ^2.1.7
  flutter_native_splash: ^2.4.0
  bloc_test: ^9.1.6
  test: ^1.24.9

flutter:
  generate: true
  uses-material-design: true

  assets:
    # Svg folder
    - assets/svg/icons/
    - assets/svg/payment_methods/

    # Images folder
    - assets/images/
    - assets/images/payment_methods/

    # Lottie folder
    - assets/lottie/no_internet/
    - assets/lottie/page_not_found/
    - assets/lottie/onboarding/
    - assets/lottie/auth/
    - assets/lottie/errors/
    
    - .env


flutter_gen:

  integrations:
    flutter_svg: true
    lottie: true

icons_launcher:
  image_path: "dev_assets/icon_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: false
    web:
      enable: true

flutter_native_splash:
  # Light
  image: "dev_assets/splash_logo.png"
  color: "#DEE2E2"

  # Dark
  image_dark: "dev_assets/splash_logo.png"
  color_dark: "#272727"
  
  # android_12:
  #   image: "dev_assets/splash_logo.png"