name: Build Flutter app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Build and test the client
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check flutter version
        run: flutter --version

      - name: Fallback
        run: ./scripts/fallback.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analysis
        run: flutter analyze

      - name: Check dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Preview dart proposed changes
        run: dart fix --dry-run

      - name: Run flutter tests
        run: flutter test